version: '3.7'

services:
  edu-chain:
    build:
      context: .
      dockerfile: Dockerfile
    image: edu-chain-image
    container_name: edu-chain-container
    restart: unless-stopped
    ports:
      - "4400:4200"
    command: sh -c "npm start"
